### PR TITLE
APIs reorganised into a nested structure

### PR DESCRIPTION
**Pull request by Mahoney**
The APIs are currently in a flat structure that makes navigating and finding them hard.

This PR will move them into a nested structure as so `api/{letter}/{provider}/{api_name}`:
```api
├── 0-9
│   ├── 1forge.com
│   │   └── 1forge.com
│   └── 1password.com
│       └── events
├── A
│   ├── ably.io
│   │   └── platform
│   └── adyen.com
│       ├── AccountService
│       ├── BalanceControlService
│       └── BalancePlatformService
├── B
└── C
```

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
TL;LGTM

image

**Comment by Mahoney** [comment]
I don't know if there's a git diff tool that can work out that all I've done is move files around... unfortunately a reorg like this seems to be too much for most git tooling.

However, eyeballing it my script has moved everything down one level too far. Looking at fixing it.

**Comment by Mahoney** [comment]
Actually it had only moved a few APIs a directory too far. Hopefully fixed that now.

**Comment by Mahoney** [comment]
@oleg-nenashev if I merge this it will presumably break the generation of [the API Templates site](https://github.com/wiremock/library.wiremock.org-sources) via Hugo when you update the submodule. Are you OK with that?

**Comment by oleg-nenashev** [comment]
@Mahoney yes, I will verify it before taking it upstream

**Pull request merged**
