### PR TITLE
feat: add Foojay discovery API

### PR DESCRIPTION
**Pull request by SimonVerhoeven**
The Foojay discovery API is used by certain tools such as SDKman to retrieve a list of available JDKs

## References

- API Documentation: https://api.foojay.io/swagger-ui
- OpenAPI original source: https://api.foojay.io/swagger/foojay-discoapi-3.0.yml

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] OpenAPI and WireMock JSON files are valid
- [x] The metadata files are added
- [x] If provided, you have a permission to use this logo

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Looks good for me, thank you! I suggest getting foojay's permission to use their logo, but it is not a blocker.

Also there a problem with the Swagger file, because it is in fact a OpennAPI YAML and not a JSON. Could we please rename it to  `discoapi_v3-swagger.yaml`? I would also use `foolay_discopapi_v3` as a slug and prefix

**Comment by SimonVerhoeven** [comment]
Sure, I'm checking if I can get permission for the logo and then perform the other changes.

**Comment by oleg-nenashev** [comment]
@SimonVerhoeven looks like the files were removed, not renamed

**Comment by SimonVerhoeven** [comment]
Ah sorry, that should be resolved.

**Review by oleg-nenashev — APPROVED** [review]
Thanks!

**Pull request merged**
